project:
  #名称
  name: uaanal
  #版本
  version: 0.0.1
  #版权年份
  copyrightYear: 2019
  indexUrl: /index.html

server:
#  servlet:
#      # 项目contextPath
#    context-path: /
  port: 8080
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/group?serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      #      db.hdp.com  ambari   bigdata ?serverTimezone=UTC&characterEncoding=utf-8
      jdbc-url: jdbc:mysql://localhost:3306/group?serverTimezone=UTC
      username: root
      password: 123456
      # 初始连接数
      initial-size: 10
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false


mybatis:
  # 搜索指定包别名
  type-aliases-package: com.ucloud.uaanal
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml
